### ISSUE TITLE
ResultBodyCollection class no have has_more field

### ISSUE THREAD

**Issue by SergeyByslyuk** [Asana/java-asana#101]
I get the field "has_more" through an http request, but it is not represented in the library(https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/models/ResultBodyCollection.java).

**Comment by rossgrambo** [comment]
Thank you for pointing this out and thank you for the PR! I went ahead and merged it, and I had planned to do a client library deploy this Friday, so this change should be included in that deploy.
