### ISSUE TITLE
Feature Request: Add Attachment to Task

### ISSUE THREAD

**Issue by cielowu** [Asana/java-asana#110]
In the API explore, we can retrieve task with its attachments with one rest call using
`https://app.asana.com/api/1.0/projects/<project_gid>/tasks?limit=10&fields=gid,name,attachments.view_url`

While with the SDK, because `Task` object does not have the field related to the attachments the `Task` attached, we have to perform an extra rest call just to fetch the attachments for one task.

Just wondering what's the reason of not having it inside the `Task` entity, as we can always set it to null as the others as a compact form?

**Comment by rossgrambo** [comment]
It looks like it just wasn't included in the model. I don't see any reason why we should add it. I'll create a task to add it! If you need it asap you can propose a PR.

**Comment by cielowu** [comment]
Sure, thanks!

**Comment by cielowu** [comment]
Created a PR: https://github.com/Asana/java-asana/pull/111

**Comment by rossgrambo** [comment]
Thank you! I reviewed and everything looks good. I merged it and as long as the build goes through it'll be included in 0.10.2!

**Comment by cielowu** [comment]
Hi @rossgrambo, just a follow-up question, I don't see the new version landed on maven, when should we expect the new deployment?

**Comment by rossgrambo** [comment]
The deploy failed on friday for something trivial. I fixed that and am deploying again now. Hopefully it will be on maven later today.

**Comment by cielowu** [comment]
Ah, thanks for the update!
