### ISSUE TITLE
Date parsing errors

### ISSUE THREAD

**Issue by eschultink** [Asana/java-asana#20]
In our logs, I'm seeing a number of messages such as `Couldn't parse date: 2015-02-27`

These seem to be coming from:
[java-asana/src/main/java/com/asana/Json.java](https://github.com/Asana/java-asana/blob/56c9a2f9c433e4d91492c819f81c41687fae302f/src/main/java/com/asana/Json.java)

So presumably the `SimpleDateFormat` in use there doesn't catch this case.

**Comment by noonhub** [comment]
@eschultink  could you include what method you are calling and with what parameters?

**Comment by eschultink** [comment]
@noonhub sorry, I'm not sure exactly where it's coming from because the API client suppresses the `ParseException`:

            } catch (ParseException e) {
                System.err.println("Couldn't parse date: " + jsonElement.getAsString());
                return null;
            }

hence I have no trace whatsoever, and can only see it after the fact in `stderr`.

The methods I call generally:

                Task task = asana.tasks.findById(taskId).execute();
		List<Task> subtasks = asana.tasks.subtasks(task.id).execute();
		List<Story> stories = asana.stories.findByTask(task.id).execute();

Looking at your REST API documentation my strong suspicion is that it's the task call, trying to parse the `dueOn` date:



![screen shot 2015-10-22 at 4 10 46 pm](https://cloud.githubusercontent.com/assets/102831/10676971/a3fafdcc-78d7-11e5-880a-0cda277d996b.png)

That appears to be the only one that's not a ISO 8601 like the client expects them all to be.

**Comment by noonhub** [comment]
@eschultink yeah, that seems reasonable. I will write a fix for this and get it pushed as soon as possible. Thanks for pointing that out :)

**Comment by noonhub** [comment]
@eschultink this should be fixed in 0.3.0 which was just deployed
