### ISSUE TITLE
Task completed is always false even though its completed

### ISSUE THREAD

**Issue by hhimanshu** [Asana/java-asana#26]
@agnoster  @tlrobinson @jacklionheart  @malcolmredheron  @txus 
This is what my code looks like  

```
import com.asana.*;
import com.asana.models.*;
import com.asana.requests.*;

public class Runner {

  public static void main(String[] args) throws Exception {
    // create a client with a personal access token
    Client client = Client.accessToken("MY_PERSONAL_ACCESS_TOKEN");

    // get the user object for yourself
    User me = client.users.me().execute();
    System.out.println("me=" + me.name);

    for (Workspace workspace : client.workspaces.findAll()) {
      final CollectionRequest<Project> projects =
          client.projects.findByWorkspace(workspace.id);
      for (Project project : projects.execute()) {
        System.out.println("workspace=" + workspace.name + ", project=" + project.name);
        System.out.println("-----------------------------------------------------------");
        final CollectionRequest<Task> tasksByProject = client.tasks.findByProject(project.id);
        for (Task task : tasksByProject.execute()) {
          System.out.println("Name=" + task.name + ", completed=" + task.completed);
        }
      }
    }
  }
}
```

When I run this, all the tasks it says `completed=false`. While many of them are completed.

Example
```
Name=Asana Api, completed=false
```

while it is completed

<img width="954" alt="screen shot 2016-03-01 at 4 07 59 pm" src="https://cloud.githubusercontent.com/assets/6589036/13446385/fd9eb1c8-dfc7-11e5-9c9d-f7e5597cb974.png">

Any ideas?

**Comment by agnoster** [comment]
When you request a list (like "tasks in a project") by default you only get the "compact" representation - id and name, usually. To request additional fields (like `completed`) see the `?opt_fields` parameter: https://asana.com/developers/documentation/getting-started/input-output-options

**Comment by hhimanshu** [comment]
@agnoster, what's the way using this java client? not by making API calls? If there is none, it's a valid bug, isn't it?

**Comment by agnoster** [comment]
I think so - if the Java client does not support sending `opt_fields` then that's probably a bug (or at least a valid feature request). I'd check the documentation and/or code first though before re-opening.

**Comment by hhimanshu** [comment]
I figured what you said could be the case and I made the change to my code. With the following change, things work as expected
```
final CollectionRequest<Task> tasksByProject = client.tasks.findByProject(project.id).query("opt_fields", "completed, name");
```

*Output*
```
Name=Asana API, completed=true
```

**Comment by agnoster** [comment]
Glad to hear it worked out! It feels like our documentation here could probably be clearer.

As a side note, I'd urge you to consider the next time that you @-mention a bunch of people on your issue that it could come off as a bit rude. Most of the people you tagged have no relation to this project at all, so while it may technically increase your odds of getting a response it's not very polite. It made me a little reluctant to respond but I figured hey, maybe no one has given you feedback to this effect before so I might as well help and then give you some gentle feedback :-) I definitely understand the impulse to want to notify as many people as possible in the hopes of getting a response, though! Consider it food for thought.

**Comment by hhimanshu** [comment]
sure @agnoster, good to learn about it. I will keep that in mind
