### ISSUE TITLE
Android studio unable to resolve Client.oauth method

### ISSUE THREAD

**Issue by mayuroks** [Asana/java-asana#27]
I am new to android development. I am trying to build a custom asana app for myself.
In my build.gradle file I added this line
```
dependencies {
  compile 'com.asana:asana:0.4.1'
}
```

Now when I try to handle oauth using below code,
```
Client client = Client.oauth(
    "ASANA_CLIENT_ID"
    "ASANA_CLIENT_SECRET"
    "urn:ietf:wg:oauth:2.0:oob"
);
```
My IDE gives me this error
```
Cannot resolve method oauth(java.lang.String, java.lang.String, java.lang.String)
```

My asana related autocompletion is working fine which means my IDE is able to recognize the library. Can anyone help me with this error ?

**Comment by shroff** [comment]
I don't see a method with the signature you are trying to call. I'm not sure what the third parameter is, but it looks like you need to call `Client.oauth(com.asana.OAuthApp)`.

`OAuthApp` has several constructors, including `OAuthApp(String clientId, String clientSecret, String redirectUri)`, `OAuthApp(String clientId, String clientSecret, String redirectUri, String accessToken)`, and several more. You can check out the source and select the appropriate constructor [here](https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/OAuthApp.java)
