### ISSUE TITLE
0.5.0 not in Maven repository

### ISSUE THREAD

**Issue by McAndze** [Asana/java-asana#40]
Nothing critical, just noticed that you changed the readme file to mention 0.5.0 in the Maven section, but it has yet to be uploaded to the repository as far as I can see. I can still only fetch v0.4.1. Would you take a look at this?

**Comment by markchua** [comment]
Thanks we'll take a look at this!

**Comment by praecipula** [comment]
@McAndze Thanks for pointing this out! I must have done something wacky on the deploy - the Java client library is the only one that has a high-touch deploy process (though we're working to make it better!) and so there's every possibility that this is the case ;)

I pushed this version to Maven and verified that [I can indeed see it](http://repo2.maven.org/maven2/com/asana/asana/), so barring some process that takes it down, you should be good to go. This version includes support for custom fields, so if you've been waiting for this, I apologize.

Cheers!

**Comment by McAndze** [comment]
@praecipula 
No worries, thanks a lot!
