### ISSUE TITLE
Introduce Asana Fast API

### ISSUE THREAD

**Issue by amitg87** [Asana/java-asana#52]
Faster version of API was released in Oct'16.
[link](https://asana.com/developers/feed/asana-fast-api-open-beta)

To enable these fast API all request need to have header - "Asana-Fast-Api:true"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694757934856/311399514842812)

**Comment by joetrollo** [comment]
This has been deprecated, as we have fully moved to the new "fast API"
