### ISSUE TITLE
Stupid exception handling in RateLimitEnforcedError

### ISSUE THREAD

**Issue by csnemeti** [Asana/java-asana#59]
Hi.

In RateLimitEnforcedError class in case there's an Exception when `retry-after` header value is processed, value is set to -1L. Knowing that this will be the value you are providing to a Thread.sleep(...) you generate a nice stacktrace.
If you'll see in attachment I ran into the following problem:

1. Got no header with name `retry-after`.
2. Due an NPE in RateLimitEnforcedError the `retryAfter` variable is set to -1.
3. In Client you are calling the Dispatcher to sleep for retryAfter milliseconds.
4. Thread.sleep(...) throws IllegalArgumentException (not InterruptedException) because provided value is negative.

![retryafter](https://user-images.githubusercontent.com/8148389/31074260-713ea7f4-a778-11e7-9bb7-3b118dfb1598.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694757934856/442480575482049)

**Comment by praecipula** [comment]
Hmm, it seems to me that the real error here is that our API isn't returning a `retry-after` header. I believe that it should always be the case that if we respond with a 429 response this header should be present.

I agree, though, that the fallback of -1 is a bad idea here - even just a dumb "try again in 1000 milliseconds" would be more robust. I'll add this to our project tracking bugs or client library opportunities for the next time we get to give our Java client library some love.

**Comment by joetrollo** [comment]
This has been corrected both in the API and in the client library.
