### ISSUE TITLE
Event Api not working since last 3-4 hours

### ISSUE THREAD

**Issue by kuldeeppoonia** [Asana/java-asana#70]
Hi Team,

From Last 3-4 hours, Event API is not giving any events. I Tried a lot but unable to diagnose it. I am using asana Java API for it.

**Comment by jjschnei** [comment]
Thanks for writing in. We had an issue with our remote jobs, which affected API events. Everything should be back to normal now.  You can read about the details of the issue here:  https://community.asana.com/t/no-events-firing-by-asana/26788/21
