### ISSUE TITLE
missing artifactid for version 0.8.0

### ISSUE THREAD

**Issue by lcmkevin** [Asana/java-asana#72]
I don't know which is the correct version right now.
I see that Asana official site said is Maven 0.6.0 , but in GitHub which state Maven 0.8.0 and my eclipse project show missing artifactid.
I tried using 0.5.2 and it can load the library.
So, which is correct ? Any hint ?

**Comment by praecipula** [comment]
0.5.2 seems correct for now, but not for long!
0.6.0 was a fix we shipped internally for our integrations team, but never deployed - I think we crossed lines a bit there when updating the docs.
0.8.0 is the version we merged into master _just yesterday at 3:21 PM_, so you just caught that this is now the state of master within hours of the merge. However, this has not yet been deployed, so updating this in your pom.xml file to 0.8.0 will have to wait a tad.

(You can always check the `maven-central` badge thing at the top of [our readme](https://github.com/Asana/java-asana#asana--) to see what the current version that has made it to maven is)

We should deploy this very soon, so if you want all the newest goodies they're just a few days away (when we finish this round of updating our client libraries). Sorry for the confusion!

**Comment by lcmkevin** [comment]
Thanks for the clarify.

**Comment by joetrollo** [comment]
This has now been deployed to Maven.
