### ISSUE TITLE
TagBase.getTasksWithTag() returns CollectionRequest<Tag> instead of CollectionRequest<Task>

### ISSUE THREAD

**Issue by berlix** [Asana/java-asana#78]
`TagBase.getTasksWithTag()` returns `CollectionRequest<Tag>`. Since it is named `getTasks...`, one would expect it to return `CollectionRequest<Task>`. I believe this is a mistake and `getTasksWithTag` not functional.

See:
https://github.com/Asana/java-asana/blob/8df262aab6ee835f8bc61a7aef02d906c33d5dbd/src/main/java/com/asana/resources/gen/TagsBase.java#L138

**Comment by rossgrambo** [comment]
Thank you @berlix . 

Yes, this is a bug with the generated code. We will resolve this with our next deploy.

Thanks,
Ross

**Comment by rossgrambo** [comment]
This has been fixed from https://github.com/Asana/java-asana/pull/82
