### ISSUE TITLE
Supporting future API changes to the ID field

### ISSUE THREAD

**Issue by christophpre** [Asana/java-asana#85]
Hi,

according to this post: 

[https://forum.asana.com/t/reminder-about-two-big-upcoming-api-changes-string-ids-and-new-sections/50416](url)

 the Asana API will change from using the numerical **id** field to the String **gid** for identifying all resources per default. This change will be effective on **August 13** according to this post [https://forum.asana.com/t/reminder-about-two-big-upcoming-api-changes-string-ids-and-new-sections/50416](url). The **id** field will then be deprecated and removed completely in future versions of the API.

Will **java-asana** be updated to support these changes? Is this project still active? Would a pull request help to address these changes?

**Comment by rossgrambo** [comment]
Hello @christophpre!

We will be doing a deploy of the client libraries next sprint (finishing the update either next week or the week after). This will include the change from id to gid. 

We're currently upgrading the tooling around the client libraries. So these will be more frequently maintained in the future.

Best,
Ross

**Comment by christophpre** [comment]
Hi,

thank you for your response. I'm glad to hear, that the library will be updated and that this project is still maintained! 

Will issues like #84 also be addressed in your next sprint?

**Comment by rossgrambo** [comment]
I don't think I'll be able to include that fix as a part of these deploys. I'll post a more specific answer on that issue.

**Comment by asufty888** [comment]
@rossgrambo - any update on the **gid** change?

**Comment by rossgrambo** [comment]
Hey @asufty888,

The PR is out to add a bunch of missing functionality and it'll be merged once it's approved. That should be within the next couple of weeks.

**Comment by rossgrambo** [comment]
@asufty888 , the update has been deployed! You can now use v0.9.0 which has **gid**s

**Comment by asufty888** [comment]
Excellent!  Thank you for the update!
