### ISSUE TITLE
Custom field does not have resource subtype

### ISSUE THREAD

**Issue by AntonyLeons** [Asana/java-asana#92]
custom field does not have a resource_subtype. and according to this form post https://forum.asana.com/t/new-task-subtypes-and-better-type-information/32047
all objects now have a ResourceWithSubtype.

So surely all model would extend ResourceWithSubtype and not resource or have the resource class modified to include sub_type?

**Comment by rossgrambo** [comment]
@AntonyLeons , you're right. Looks like Custom Field was missing the import. I also took this as an opportunity for the other resources to extend ResourceWithSubtype instead of declaring it themselves.

Thanks!
