### ISSUE TITLE
How do I create a section?

### ISSUE THREAD

**Issue by dotneet** [Asana/java-asana#99]
Is it still not supported with this library?

**Comment by dotneet** [comment]
I've resolved this issue but I'm not sure instantiating SectionBase directory is proper way.
Does this code have problem?

```scala
val sectionsResource = new SectionsBase(asanaClient)
sectionsResource.createInProject(projectId)
  .data("name", name)
  .execute()
```

**Comment by rossgrambo** [comment]
Hey @dotneet,

I'm sorry I never saw this request. I ended up adding .sections to the Client class, and you should now be able to use that on 0.10.3
